### ISSUE TITLE
valgrind: m_machine.c:2392 (vgPlain_machine_get_hwcaps): Assertion 'r == 0' failed

### ISSUE THREAD

**Issue by ctlinglingliu** [loongson/valgrind-loongarch64#2]
3A5000+kylin上编译完成后，运行valgrind的时候报错如下：
valgrind: m_machine.c:2392 (vgPlain_machine_get_hwcaps): Assertion 'r == 0' failed
另外，源码中需要修改VEX/pub/libvex_basictypes.h文件中的#elif defined(__loongarch__) //&& (__loongarch_grlen == 64)，将__loongarch_grlen == 64注释掉，否则架构判断不通过

**Comment by FreeFlyingSheep** [comment]
这说明你的gcc版本太低了，`old-world` 分支是在 Loongnix-Server 8.4 系统上验证过的 :)
